<a href="https://colab.research.google.com/github/Supakornnn/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสรางข้อมูล)
การเก็บข้อมูลหลายๆตัวไว้ด้วยกันอย่างเป็นระเบียบ

## `list()`

- เก็บอะไรก็ได้
- ลำดับในการเก็บมีความสำคัญ

In [ ]:
list_a = [1,2,3,4,5,6] # วงเล็บของ lsit [] square brackets

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b = ['ab',2,3.14,list_a]

In [ ]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

### indexing การชี้สมาชิกใน list ด้วย เลขลำดับของ list

In [ ]:
list_a[3]

4

In [ ]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b[3][4]

5

In [ ]:
list_a[6] #ถ้าไปเรียกลำดับที่ไม่มีในlist ก็จะ error

IndexError: ignored

In [ ]:
list_a[-1] #index -1 คือตัวสุดท้ายของ list 

6

In [ ]:
list_a[-4]

3

### การสร้าง`list()`

In [ ]:
list_x1 = [] #เเบบที่1 
list_x2 = list() #เเบบที่2

In [ ]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย `append()`

In [ ]:
list_x1.append(2)

In [ ]:
list_x1

[2]

In [ ]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [ ]:
list_x1[0]

2

In [ ]:
list_x1[-1]

4

In [ ]:
list_x2

[]

In [ ]:
list_x2.append('ha')

In [ ]:
list_x2

['ha', 'ha', 'ha']

### ลบสมาชิกออกจาก list

In [ ]:
list_x1.append('ha')

In [ ]:
list_x1

[2, 'ha']

In [ ]:
list_x1.pop()
print(list_x1)

[2]


### len() ตรวจสอบสมาชิกของ list

In [ ]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [ ]:
len(list_a)

6

### String is a list of characters

In [ ]:
st_stat = 'Department of Statistics, Faculty of Science'

In [ ]:
st_stat[10]

' '

In [ ]:
len(st_stat)

44

## list Slicing `:`

`list[จุดเริ่มต้น (ทึบ) : จุดสุดท้าย (โปร่ง)]`

`list[จุดเริ่มต้น (ทึบ) : จุดสุดท้าย (โปร่ง): step]`

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_a[2]

3

### `:` colon

In [ ]:
list_a[-3:]  # : colon

[4, 5, 6]

In [ ]:
list_a[:4] # : colon

[1, 2, 3, 4]

In [ ]:
list_a[1:4]

[2, 3, 4]

In [ ]:
list_a[:]

[1, 2, 3, 4, 5, 6]

### step

In [ ]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [ ]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [ ]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### `range()`

In [ ]:
range(21)

range(0, 21)

In [ ]:
a = list(range(21))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

## HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)

- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 01:10:15


In [ ]:
#01:02:03

a = (1*60*60) + (2*60) + 3
print(f'01:02:03 เเปลงเป็นวินาทีได้ {a} วินาที')

01:02:03 เเปลงเป็นวินาทีได้ 3723 วินาที


In [ ]:
#12:30:15

b = (12*60*60) + (30*60) + 15
print(f'12:30:15] เเปลงเป็นวินาทีได้ {b} วินาที')

12:30:15] เเปลงเป็นวินาทีได้ 45015 วินาที


In [ ]:
#13:41:07

c = (13*60*60) + (41*60) + 7
print(f'13:41:07] เเปลงเป็นวินาทีได้ {c} วินาที')

13:41:07] เเปลงเป็นวินาทีได้ 49267 วินาที


In [1]:
#21:30:15
d = (21*60*60) + (30*60) +15
print(f'21:30:15] เเปลงเป็นวินาทีได้ {d} วินาที')

21:30:15] เเปลงเป็นวินาทีได้ 77415 วินาที


In [2]:
#01:10:15
e = (1*60*60) + (10*60) +15
print(f'01:10:15] เเปลงเป็นวินาทีได้ {e} วินาที')

01:10:15] เเปลงเป็นวินาทีได้ 4215 วินาที


## Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวเลขกำกับ
- ลำดับไม่มีความสำคัญ

### สร้าง Dictionary

### การชี้ สมาชิกใน Dictionary

In [4]:
dict_a = {1:'Happy','N':'New','2022': 'Year'} # { } curly packets

In [5]:
dict_a[1]

'Happy'

In [7]:
dict_a['N']

'New'

In [8]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [9]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

### การเพิ่มสมาชิกลงไปใน Dictionary

In [10]:
dict_a[7] = 3.14

In [11]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [12]:
dict_a['N'] = 'NNNNEEEEWWWW'

In [13]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEEEEWWWW'}

## Numpy Array

- เก็บได้เเต่ตัวเลข
- อ้างอิงโดยใช้ พิกัด (2มิติ ก็มองเป็นMatrix)

### 1D array

In [14]:
import numpy

In [19]:
list_A = [1,2,3,4,5]

In [15]:
arr_a = numpy.array([1,2,3,4,5])

In [16]:
arr_a

array([1, 2, 3, 4, 5])

In [21]:
list_A

[1, 2, 3, 4, 5]

In [17]:
arr_a[0]

1

In [22]:
list_A[0]

1

In [23]:
5* arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [24]:
5* list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [25]:
arr_b = numpy.array([10,20,30,40,50])

In [26]:
print(arr_a)

[1 2 3 4 5]


In [27]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

In [33]:
arr_a.shape

(5,)

###2D array

In [29]:
import numpy as np

In [30]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [31]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2_z.shape

(2, 3)

###`np.zeros()`

In [35]:
arr2_3_5_0 = np.zeros ((3,5))

In [36]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
arr2_3_5_0[1,2] = 9 #กำหนดค่า

In [42]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
arr2_3_5_0[1,2] #ชี้

9.0

In [46]:
print(list_A) # เปลี่ยนค่าใน list()
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 'Christmas']
[1, 2, 3, 4, 'Christmas']


###`np.ones()`

In [47]:
arr2_4_5_1 = np.ones ((4,5))

In [48]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
arr2_4_5_200 = 200*np.ones ((4,5))

In [51]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix operations

การบวก ลบ Matrix $M \pm N$ บวกลบตัวที่อยู๋ตำเเหน่งเดียวกัน

In [52]:
arr2_4_5_200 + arr2_3_5_0 #การบวก ลบ Matrix shape ต้องเท่ากัน

ValueError: ignored

In [53]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

### การคูณ Matrix 
- $aM$ scalar คูณ Matrix (scalarคูณกระจายเข้าไปทุกตัวของ Matrix)
- $M\times N$ คูณ Matrix (เเถวคูณหลัก)

$aM$

In [54]:
5* arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

$M\times N$ (dot product)
- (m,n) $\times$ (n,o) = (m,o) (shape)

In [56]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [57]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [58]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [59]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

axc, bxc,  

In [60]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [61]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

cxa, cxb

In [62]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [66]:
mat_X = np.dot(mat_c,mat_b)
print (mat_X)

[[  8  16 -11]
 [ 16  32 -22]
 [ 25  50 -28]]


In [64]:
mat_a * mat_b  #คูณตัวตำเเหน่งเดียวกัน

array([[  2,   6,  25],
       [  8,  24, -49]])

### Matrix Slicing

In [67]:
mat_X[:2,:2]

array([[ 8, 16],
       [16, 32]])

HW 3


1. สร้าง array ที่เป็นรูปต้น Chrismas
2. Slice เลข 1 ออกมาเป็น array HW3 ด้วยการ slice ครั้งเดียว

In [70]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
HW3[:,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
็HW3

SyntaxError: ignored

## Pandas Dataframe (เเยกออกไปเป็น Notebook เฉพาะ)